CI/CD deploy to azure
it-pebune/ani-research-web pull request #43
Opened 2022-02-02 16:35 UTC by octavianpur

- baseline CI/CD action

2022-02-03 21:33 UTC, catalin-apostu requested changes

2022-02-05 12:19 UTC, octavianpur commented on .github/workflows/azure-static-web-apps-brave-forest-0cca66303.yml
> +name: Azure Static Web Apps CI/CD - deprecated
removed this action file since is no longer required

2022-02-05 12:21 UTC, octavianpur commented on .github/workflows/azure-static-web-apps-white-mud-059586e03.yml
> +    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
fixed with new commits 
- removed the build and deploy on PR
- action will build and deploy the app only on push to main branch

2022-02-05 13:52 UTC, octavianpur commented on .github/workflows/azure-static-web-apps-white-mud-059586e03.yml
> +  close_pull_request_job:
- I removed also the close PR job

2022-02-07 20:40 UTC, closed without merging